In [1]:
import numpy as np

#### Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;


Произведение матрицы $AB$ и $BA$  не определены, т.к. количество столбцов первой матрицы не равно количество строк во второй матрице.

    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;


Произведение матрицы $AB$ определено, размерность результата $2\times 3$.  
Произведение матрицы $BA$ не определено.

    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;


Произведение матрицы $AB$ определено, размерность результата $8\times 8$.  
Произведение матрицы $BA$ определено, размерность результата $3\times 3$.  

    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Произведение матрицы $AB$ определено, размерность результата $4\times 4$.  
Произведение матрицы $BA$ определено, размерность результата $4\times 4$.    

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



 $A + B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}+\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$  
 $A \cdot B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Сумма матриц равно \n {A + B}')
print(f'Произведение матриц равно \n {np.dot(A,B)}')

Сумма матриц равно 
 [[ 5 -3]
 [ 3  5]]
Произведение матриц равно 
 [[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

$3A-2B+4C = 3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} -2 \cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+ 4 \cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = $


$=\begin{pmatrix}
3 +0 +8 & 21 -10 -16\\ 
9 -4 + 4 & -18 +2 + 4
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9  & -12
\end{pmatrix}.$

In [3]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Сумма матриц равна \n {3 * A -2 *B + 4*C}')

Сумма матриц равна 
 [[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^T=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3 \\ 
5 \cdot 4 -2 \cdot 1 & 5 \cdot 5  -2 \cdot (-2) & 5\cdot 2 - 2 \cdot 3 \\ 
2 \cdot 4 +3 \cdot 1 & 2 \cdot 5  +3 \cdot (-2) & 2\cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\ 
11 & 4 & 13
\end{pmatrix}$

$A^TA= \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}= \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3\\ 
1 \cdot 4 -2 \cdot 5 + 3 \cdot 2 & 1 \cdot 1 -2 \cdot (-2) + 3 \cdot 3
\end{pmatrix} =  \begin{pmatrix}
 45& 0\\ 
 0 & 14 
\end{pmatrix}.$


In [4]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Произведение A и A.T равно \n {np.dot(A, A.T)}')
print(f'Произведение A.T и A равно \n {np.dot(A.T, A)}')

Произведение A и A.T равно 
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение A.T и A равно 
 [[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def size_matrix(A):
    if len(A)> 0:
        spam = len(A[0])
        for i in range(len(A)):
            if spam != len(A[i]):
                raise ValueError(f'Исходные данные не содержат матрицу')
        return len(A) , spam 
    else:
        return 0, 0
    
def init_matrix(rows_count, cols_count):
    result = [[0] * rows_count for i in range(cols_count)]
    return result

def function_dot(A, B):
    ax, ay = size_matrix(A)
    bx, by = size_matrix(B)
    if (ay != bx):
        raise ValueError(f'Произведение матриц не определено. Размеры не соответствуют')
    if (ay == 0):
        return 0
    else:
        result = init_matrix(ax, by)
        for i in range(ax):
            for j in range(by):
                for k in range(ay):
                    result[i][j] += A[i][k] * B[k][j]
        return result
       

In [6]:
A = [[4, 1], [5, -2], [2, 3]]
B = [[4, 5, 2], [1, -2, 3]]
print(f'Произведение матриц равно \n {function_dot(A,B)}')

Произведение матриц равно 
 [[17, 18, 11], [18, 29, 4], [11, 4, 13]]


#### Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^{2}x + cos^{2}x = 1;$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 = 180;$$

   в)
$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 - 2 \cdot 4 + 1 & 8 - 2 \cdot 5 + 2 & 9 - 2 \cdot 6 + 3
\end{vmatrix} = 
\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
0 & 0 & 0
\end{vmatrix} = 0.$$  
<br>
Матрица имеет нулевую строку или столбец, то определитель равен нулю

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;  
для 2 матриц одинакового размера $$det(AA)=detA\cdot detA = 16.$$

    
   б) $det(A^{T})$;
    
$$detA^{T}=detA=4.$$

   в) $det(2A)$.
    
 Умножение строки или столбца матрицы на число $2$ приведет к умножению определителя матрицы на то же число.  
$det(2A) = 2 \cdot det(A) = 8$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Найдем определитель матрицы:<br>
$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}  =
\begin{vmatrix}
-2 & 7 & -3\\ 
4 + 2 \cdot(-2) & -14 + 2 \cdot(7)  & 6 + 2 \cdot(-3) \\ 
-3 & 7 & 13
\end{vmatrix} =
\begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0 \\ 
-3 & 7 & 13
\end{vmatrix} = 0
$$  
Т.к. первая и вторая строка линейно зависимы, то определитель равен 0, т.е. матрица вырождена

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

1) Третья строка линейно зависима от первой и второй строки, поэтому ее можно отбросить.   
2) Из второй вычтем первую и получим следующую матрицу:  
$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix};$

Получаем, что ранг матрицы равен 2

In [8]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2



   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

1) Третья строка линейно зависима от первой и второй строки, поэтому ее можно отбросить.   
2) Переставим строку 3 и 1:  
$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 2 & 1
\end{pmatrix}.$<br>
2) Переставим столбцы 4 и 2:  
$\begin{pmatrix}
2 & 6 & 5 & 3\\ 
0 & 2 & 2 & 0\\ 
0 & 1 & 2 & 0
\end{pmatrix}.$<br>
3) Домножим на -2 третью строку и добавим ко второй, а после поменяем местами:  
$\begin{pmatrix}
2 & 6 & 5 & 3\\ 
0 & 1 & 2 & 0\\ 
0 & 0 & -2 & 0
\end{pmatrix}.$<br>

Получаем, что ранг матрицы равен 3

In [9]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
v = [2, 3, 4, 6]

a = np.array([x, y, z, v])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
